### PR TITLE
Add Duration::span_v() which also returns the closure's return value

### PR DESCRIPTION
**Pull request by nabijaczleweli**
I found myself needing to measure resultsome closures, this seemed like a simple fix.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Unfortunately though this crate is sort of in limbo and is essentially at the point where we're not accepting breaking changes right now. This is unfortunately a breaking change to the signature of the function :(

**Comment by nabijaczleweli** [comment]
:sadfaec:
Maybe as another function (`span_r` or w/e, I'm bad at naming), though?

**Comment by alexcrichton** [comment]
Perhaps, although we're not currently developing this library, so we've been holding off on new features until we can figure out where it's going.

**Comment by nabijaczleweli** [comment]
So what's the status on this? Should I just use [a manual implementation](https://github.com/nabijaczleweli/tweetr/blob/457d6a27a0ba8293e9643443f08204e970cb7493/src/util.rs#L30-L53) and fuck off or...?

**Comment by nabijaczleweli** [comment]
TBH I wanted this because `time::Duration` is reexported in `chrono::Duration`

**Comment by alexcrichton** [comment]
@nabijaczleweli I'd recommend a local implementation for now, the libs team would probably prefer to overhaul this type entirely before piecemeal adding methods here and there for now.

**Comment by nabijaczleweli** [comment]
OK then

**Pull request closed without merging**
